import type { NextConfig } from "next";

/**
 * The four package pages (yourkey.app/sales, /time, /communication, /leadership) are static HTML in
 * public/packages/, generated by the app repo (yourkey-app: scripts/web/package-pages.ts) from the
 * same claims-checked copy the in-app paywalls use. Do not edit those files here — regenerate them.
 * Until the production purchase link is set in the app repo, they are previews: no checkout, noindex.
 */
const PACKAGE_PAGES = ["sales", "time", "communication", "leadership"];

const nextConfig: NextConfig = {
  async rewrites() {
    return PACKAGE_PAGES.map((id) => ({ source: `/${id}`, destination: `/packages/${id}.html` }));
  },
  /* The July site's /seminar and /mastermind described a seminar and an AI council the app no longer
     has under those names (rebuilt 2026-10-04). Old links land on what is true today. */
  async redirects() {
    return [
      { source: "/seminar", destination: "/packages", permanent: true },
      { source: "/mastermind", destination: "/tools", permanent: true },
    ];
  },
};

export default nextConfig;
